// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudwego/eino/components/model (interfaces: BaseChatModel)

// Package model is a generated GoMock package.
package model

import (
	context "context"
	reflect "reflect"

	model "github.com/cloudwego/eino/components/model"
	schema "github.com/cloudwego/eino/schema"
	gomock "github.com/golang/mock/gomock"
)

// MockBaseChatModel is a mock of BaseChatModel interface.
type MockBaseChatModel struct {
	ctrl     *gomock.Controller
	recorder *MockBaseChatModelMockRecorder
}

// MockBaseChatModelMockRecorder is the mock recorder for MockBaseChatModel.
type MockBaseChatModelMockRecorder struct {
	mock *MockBaseChatModel
}

// NewMockBaseChatModel creates a new mock instance.
func NewMockBaseChatModel(ctrl *gomock.Controller) *MockBaseChatModel {
	mock := &MockBaseChatModel{ctrl: ctrl}
	mock.recorder = &MockBaseChatModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBaseChatModel) EXPECT() *MockBaseChatModelMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockBaseChatModel) Generate(ctx context.Context, input []*schema.Message, opts ...model.Option) (*schema.Message, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, input}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Generate", varargs...)
	ret0, _ := ret[0].(*schema.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockBaseChatModelMockRecorder) Generate(ctx, input interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, input}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockBaseChatModel)(nil).Generate), varargs...)
}

// Stream mocks base method.
func (m *MockBaseChatModel) Stream(ctx context.Context, input []*schema.Message, opts ...model.Option) (*schema.StreamReader[*schema.Message], error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, input}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Stream", varargs...)
	ret0, _ := ret[0].(*schema.StreamReader[*schema.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stream indicates an expected call of Stream.
func (mr *MockBaseChatModelMockRecorder) Stream(ctx, input interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, input}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockBaseChatModel)(nil).Stream), varargs...)
}
